name: 通知伟哥
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '1 */2 * * *'
jobs:
  build:
    runs-on: macos-latest       
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/AmyTelecom/YangMao3.git ~/YangMao3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x          
      - name: npm install
        run: |
          cd ~/YangMao3/YangMao      
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
          
          
      - name: '【通知伟哥】'
        run: |  
          cd ~/YangMao3/YangMao
          node 伟哥.js    
      - name: '【通知伟哥】'
        run: |  
          cd ~
          node sendNotify.js    
        env:
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
